# Nombre lógico de la aplicación en Spring (logs/metrics).
spring.application.name=ms-usuarios

# — Servidor ————————————————————————————————————————
server.port=8080

# — Base de datos MySQL ——————————————————————————————
spring.datasource.url=jdbc:mysql://localhost:3306/ms_usuarios_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# — JPA / Hibernate ——————————————————————————————————
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# — Swagger / OpenAPI ————————————————————————————————
springdoc.swagger-ui.path=/swagger-ui.html
